name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set @natterstefan-bot as committer
        run: |
          git config user.name "natterstefan Bot"
          git config user.email "natterstefan-bot@users.noreply.github.com"

      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install
      - run: yarn lint
      - run: yarn test
